### ISSUE TITLE
WMTS Error

### ISSUE THREAD

**Issue by benhosmer** [ossimlabs/omar#6]
`java.lang.Exception: Operation null is not supported` after visiting `/wmts?GetCapabilities`
The stack trace:

```
wmts_1    | Grails application running at http://localhost:8080 in environment: production
wmts_1    | ERROR grails.app.controllers.omar.wmts.WmtsController - Operation null is not supported
```

**Comment by benhosmer** [comment]
Shouldn't this return a 404?

**Comment by gpotts** [comment]
Maybe,  this is probably a default error if an exception occurs anywhere on the system.  As long as 200 is not returned then we are Ok for now.  Probably eventually need custom messaging that is more toward the OGC Service standards for WMS, WFS, WMTS.   Just have not done those yet.  Basically,  need to add proper messaging output that adheres to the spec.

I think all Exceptions are probably mapped to 500 errors or internal server errors.

**Comment by benhosmer** [comment]
The response header shows 400, but it doesn't show in the body returned which is where my confusion came from. It looks like here: https://github.com/ossimlabs/omar/blob/master/plugins/omar-wmts/grails-app/controllers/omar/wmts/WmtsController.groovy#L119

**Comment by gpotts** [comment]
Hello Ben:

Usually the body is whatever the application wants it to be and the  important thing is if the response code is set for programmatic testing. As long as the response code is set we are good.

Take care

Garrett

**Comment by benhosmer** [comment]
If a user or application is using this service and makes a bad request, how does `java.lang.Exception: Operation null is not supported after visiting /wmts?GetCapabilities` tell them they've made a bad request as opposed to an error occurred in the application?

The HTTP specification also talks a bit about this: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

> 10.4 Client Error 4xx
> The 4xx class of status code is intended for cases in which the client seems to have erred. Except when responding to a HEAD request, the server SHOULD include an entity containing an explanation of the error situation, and whether it is a temporary or permanent condition. These status codes are applicable to any request method. User agents SHOULD display any included entity to the user.

**Comment by gpotts** [comment]
If you are accessing it programmatically you will probably be testing the return code not the message body.   Like I said before,  I need to revisit to standardize the messages
